<?php

namespace Aeria\RenderEngine\Views;

use Aeria\RenderEngine\AbstractClasses\ViewAbstract;

/**
 * CoreView is a simple view, which renders a php file
 * 
 * @category Render
 * @package  Aeria
 * @author   Simone Montali <simone.montali@caffeina.com>
 * @license  https://github.com/caffeinalab/aeria/blob/master/LICENSE  MIT license
 * @link     https://github.com/caffeinalab/aeria
 */
class CoreView extends ViewAbstract
{
    /**
     * Returns the view's name, generated by snakecasing the filename
     *
     * @return string the view name
     *
     * @access public
     * @since  Method available since Release 3.0.0
     */
    public function name():string
    {
        if (preg_match_all(
            '/^([\/][a-zA-Z\/0-9\ \-]+)\/(([a-zA-Z\ -_%$£]+).php)+$/',
            $this->view_path,
            $matches
        )
        ) {
            return toSnake(basename($this->view_path, '.php'));
        } else {
            throw new Exception("Unable to get filename for file: ".$this->view_path);
        }


    }
}